### ISSUE TITLE
What are the required Apache settings?

### ISSUE THREAD

**Issue by jkanalakis** [gilbitron/Arrest-MySQL#9]
After copying files to the server's root directory, I'm unable to get a list of rows from the database. A call without specifying any table results in a structured JSON "Table Not Found" error from Arrest-MySQL. However, appending the table name (http://api.example.com/customers) does not return a JSON error, but rather an Apache page not found error, "The requested URL /customers was not found on this server."  - given that the "customers" table does in fact exist. 

This seems to work fine with my MAMP setup in MacOS, but not with my hosted Apache server. I have mod_rewrite enabled and the .htaccess included in this project. What other Apache settings are needed?

Thank you,

John K.

**Comment by anasmatic** [comment]
I'm in a situation like this, would you please tell what you did to fix that.

**Comment by amsakanna** [comment]
I too face this problem. What is the solution?

works in localhost but not when deployed in godaddy server.

**Comment by dmyers2004** [comment]
Try this one

RewriteEngine On

RewriteBase /

RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d

RewriteRule ^(.*)$ index.php/$1 [L]

**Comment by amsakanna** [comment]
I have this. Is it any different?

<IfModule mod_rewrite.c>
RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php/$1 [L]
</IfModule>
